domain = [
    {'fileName': 'docfile.doc', 'filePathName': 'docfile.doc', 'extensionType': '.doc', 'expectedStatus': 'allowed'},
    {'fileName': 'docxfile.docx', 'filePathName': 'docxfile.docx', 'extensionType': '.docx',
     'expectedStatus': 'allowed'},
    {'fileName': 'giffile.gif', 'filePathName': 'giffile.gif', 'extensionType': '.gif', 'expectedStatus': 'allowed'},
    {'fileName': 'jpegfile.jpeg', 'filePathName': 'jpegfile.jpeg', 'extensionType': '.jpeg',
     'expectedStatus': 'allowed'},
    {'fileName': 'cyglaunch.exe', 'filePathName': 'cyglaunch.exe', 'extensionType': '.exe',
     'expectedStatus': 'disallowed'},
    {'fileName': 'jpgfile.jpg', 'filePathName': 'jpgfile.jpg', 'extensionType': '.jpg', 'expectedStatus': 'allowed'},
    {'fileName': 'pngfile.png', 'filePathName': 'pngfile.png', 'extensionType': '.png', 'expectedStatus': 'allowed'},
    {'fileName': '7zfile.7z', 'filePathName': '7zfile.7z', 'extensionType': '.7z', 'expectedStatus': 'allowed'},
    {'fileName': 'csvfile.csv', 'filePathName': 'csvfile.csv', 'extensionType': '.csv', 'expectedStatus': 'allowed'},
    {'fileName': 'gzfile.tar.gz', 'filePathName': 'gzfile.tar.gz', 'extensionType': '.gz', 'expectedStatus': 'allowed'},
    {'fileName': '3gpfile.3gp', 'filePathName': '3gpfile.3gp', 'extensionType': '.3gp', 'expectedStatus': 'allowed'},
    {'fileName': 'mp4file.mp4', 'filePathName': 'mp4file.mp4', 'extensionType': '.mp4', 'expectedStatus': 'allowed'},
    {'fileName': 'webmfile.webm', 'filePathName': 'webmfile.webm', 'extensionType': '.webm',
     'expectedStatus': 'allowed'},
    {'fileName': 'zipfile.zip', 'filePathName': 'zipfile.zip', 'extensionType': '.zip', 'expectedStatus': 'allowed'},
    {'fileName': 'allowed_extensions_inputfile.xls', 'filePathName': 'allowed_extensions_inputfile.xls',
     'extensionType': '.xls', 'expectedStatus': 'allowed'},
    {'fileName': 'xlsxfile.xlsx', 'filePathName': 'xlsxfile.xlsx', 'extensionType': '.xlsx',
     'expectedStatus': 'allowed'},
    {'fileName': 'txtfile.txt', 'filePathName': 'txtfile.txt', 'extensionType': '.txt', 'expectedStatus': 'allowed'},
    {'fileName': 'sqlfile.sql', 'filePathName': 'sqlfile.sql', 'extensionType': '.sql', 'expectedStatus': 'allowed'},
    {'fileName': 'jsonfile.json', 'filePathName': 'jsonfile.json', 'extensionType': '.json',
     'expectedStatus': 'allowed'},
    {'fileName': 'dobfile.docb', 'filePathName': 'dobfile.docb', 'extensionType': '.docb', 'expectedStatus': 'allowed'},
    {'fileName': 'docmfile.docm', 'filePathName': 'docmfile.docm', 'extensionType': '.docm',
     'expectedStatus': 'allowed'},
    {'fileName': 'dotfile.dot', 'filePathName': 'dotfile.dot', 'extensionType': '.dot', 'expectedStatus': 'allowed'},
    {'fileName': 'dotmfile.dotm', 'filePathName': 'dotmfile.dotm', 'extensionType': '.dotm',
     'expectedStatus': 'allowed'},
    {'fileName': 'dotxfile.dotx', 'filePathName': 'dotxfile.dotx', 'extensionType': '.dotx',
     'expectedStatus': 'allowed'},
    {'fileName': 'odtfile.odt', 'filePathName': 'odtfile.odt', 'extensionType': '.odt', 'expectedStatus': 'allowed'},
    {'fileName': 'pdf.pdf', 'filePathName': 'pdf.pdf', 'extensionType': '.pdf', 'expectedStatus': 'allowed'},
    {'fileName': 'pptfile.ppt', 'filePathName': 'pptfile.ppt', 'extensionType': '.ppt', 'expectedStatus': 'allowed'},
    {'fileName': 'pptxfile.pptx', 'filePathName': 'pptxfile.pptx', 'extensionType': '.pptx',
     'expectedStatus': 'allowed'},
    {'fileName': 'rtffile.rtf', 'filePathName': 'rtffile.rtf', 'extensionType': '.rtf', 'expectedStatus': 'allowed'},
    {'fileName': 'xltxfile.xltx', 'filePathName': 'xltxfile.xltx', 'extensionType': '.xltx',
     'expectedStatus': 'allowed'},
    {'fileName': 'xltmfile.xltm', 'filePathName': 'xltmfile.xltm', 'extensionType': '.xltm',
     'expectedStatus': 'allowed'},
    {'fileName': 'odsfile.ods', 'filePathName': 'odsfile.ods', 'extensionType': '.ods', 'expectedStatus': 'allowed'},
    {'fileName': 'p12file.p12', 'filePathName': 'p12file.p12', 'extensionType': '.p12', 'expectedStatus': 'allowed'},
    {'fileName': 'potfile.pot', 'filePathName': 'potfile.pot', 'extensionType': '.pot', 'expectedStatus': 'allowed'},
    {'fileName': 'potmfile.potm', 'filePathName': 'potmfile.potm', 'extensionType': '.potm',
     'expectedStatus': 'allowed'},
    {'fileName': 'potxfile.potx', 'filePathName': 'potxfile.potx', 'extensionType': '.potx',
     'expectedStatus': 'allowed'},
    {'fileName': 'ppsfile.pps', 'filePathName': 'ppsfile.pps', 'extensionType': '.pps', 'expectedStatus': 'allowed'},
    {'fileName': 'ppsxfile.ppsx', 'filePathName': 'ppsxfile.ppsx', 'extensionType': '.ppsx',
     'expectedStatus': 'allowed'},
    {'fileName': 'pptm.pptm', 'filePathName': 'pptm.pptm', 'extensionType': '.pptm', 'expectedStatus': 'allowed'},
    {'fileName': 'rarfile.rar', 'filePathName': 'rarfile.rar', 'extensionType': '.rar', 'expectedStatus': 'allowed'},
    {'fileName': 'cyglaunch.txt', 'filePathName': 'cyglaunch.exe', 'extensionType': '.exe',
     'expectedStatus': 'disallowed'},
    {'fileName': 'exetotxt.txt', 'filePathName': 'exetotxt.txt', 'extensionType': '.txt',
     'expectedStatus': 'disallowed'},
    {'fileName': 'txttoexe.exe', 'filePathName': 'txttoexe.exe', 'extensionType': '.exe',
     'expectedStatus': 'disallowed'}]
