a = {"data": {"scheduleId": "scd:hirepro-consultancy-pvt-ltd:7312e045-8fa9-47f5-a75a-e7fb3fc6c286", "candidates": [
    {"candidateId": "030330000000067", "products": [{"productId": "prd:pfpi:a98de195-aaee-4e7d-86b7-af847cc09a82",
                                                     "results": {"normId": "global", "scores": {"items": [
                                                         {"name": "Tension-Inquiétude", "value": "32","type": "number"},
                                                         {"name": "Tension-Inquiétude", "value": "8", "type": "number"},
                                                         {"name": "Tension-Inquiétude", "value": "24","type": "number"},
                                                         {"name": "Tension-Inquiétude", "value": "5", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "24", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "3", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "18", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "0", "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "33", "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "9", "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "25", "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "6", "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "24", "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "5", "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "18", "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "3", "type": "number"},
                                                         {"name": "Enthousiasme", "value": "24", "type": "number"},
                                                         {"name": "Enthousiasme", "value": "3", "type": "number"},
                                                         {"name": "Enthousiasme", "value": "18", "type": "number"},
                                                         {"name": "Enthousiasme", "value": "0", "type": "number"},
                                                         {"name": "Sociabilité", "value": "24", "type": "number"},
                                                         {"name": "Sociabilité", "value": "4", "type": "number"},
                                                         {"name": "Sociabilité", "value": "16", "type": "number"},
                                                         {"name": "Sociabilité", "value": "0", "type": "number"},
                                                         {"name": "Energie", "value": "36", "type": "number"},
                                                         {"name": "Energie", "value": "6", "type": "number"},
                                                         {"name": "Energie", "value": "28", "type": "number"},
                                                         {"name": "Energie", "value": "2", "type": "number"},
                                                         {"name": "Assertivité", "value": "29", "type": "number"},
                                                         {"name": "Assertivité", "value": "8", "type": "number"},
                                                         {"name": "Assertivité", "value": "21", "type": "number"},
                                                         {"name": "Assertivité", "value": "3", "type": "number"},
                                                         {"name": "Innovation", "value": "30", "type": "number"},
                                                         {"name": "Innovation", "value": "7", "type": "number"},
                                                         {"name": "Innovation", "value": "24", "type": "number"},
                                                         {"name": "Innovation", "value": "3", "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "26", "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "1", "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "16", "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "0", "type": "number"},
                                                         {"name": "Analyse de soi", "value": "27", "type": "number"},
                                                         {"name": "Analyse de soi", "value": "6", "type": "number"},
                                                         {"name": "Analyse de soi", "value": "21", "type": "number"},
                                                         {"name": "Analyse de soi", "value": "2", "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "32", "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "2", "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "24", "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "0", "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "36", "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "7", "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "26", "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "3", "type": "number"},
                                                         {"name": "Attention à autre", "value": "30", "type": "number"},
                                                         {"name": "Attention à autre", "value": "3", "type": "number"},
                                                         {"name": "Attention à autre", "value": "24", "type": "number"},
                                                         {"name": "Attention à autre", "value": "0", "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "37", "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "5", "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "29", "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "3", "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "32", "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "10", "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "24", "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "6", "type": "number"},
                                                         {"name": "Plannification organisation", "value": "32", "type": "number"},
                                                         {"name": "Plannification organisation", "value": "4", "type": "number"},
                                                         {"name": "Plannification organisation", "value": "24", "type": "number"},
                                                         {"name": "Plannification organisation", "value": "2", "type": "number"},
                                                         {"name": "Autodiscipline", "value": "36", "type": "number"},
                                                         {"name": "Autodiscipline", "value": "4", "type": "number"},
                                                         {"name": "Autodiscipline", "value": "28", "type": "number"},
                                                         {"name": "Autodiscipline", "value": "2", "type": "number"},
                                                         {"name": "Controle de soi", "value": "33", "type": "number"},
                                                         {"name": "Controle de soi", "value": "4", "type": "number"},
                                                         {"name": "Controle de soi", "value": "25", "type": "number"},
                                                         {"name": "Controle de soi", "value": "1", "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "39", "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "7", "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "29", "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "3", "type": "number"},
                                                         {"name": "Proactivité", "value": "27", "type": "number"},
                                                         {"name": "Proactivité", "value": "5", "type": "number"},
                                                         {"name": "Proactivité", "value": "19", "type": "number"},
                                                         {"name": "Proactivité", "value": "1", "type": "number"},
                                                         {"name": "Ouverture", "value": "109", "type": "number"},
                                                         {"name": "Ouverture", "value": "1", "type": "number"},
                                                         {"name": "Ouverture", "value": "91", "type": "number"},
                                                         {"name": "Ouverture", "value": "0", "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "102", "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "4", "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "86", "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "2", "type": "number"},
                                                         {"name": "Extraversion", "value": "106", "type": "number"},
                                                         {"name": "Extraversion", "value": "4", "type": "number"},
                                                         {"name": "Extraversion", "value": "90", "type": "number"},
                                                         {"name": "Extraversion", "value": "2", "type": "number"},
                                                         {"name": "Agréabilité", "value": "126", "type": "number"},
                                                         {"name": "Agréabilité", "value": "6", "type": "number"},
                                                         {"name": "Agréabilité", "value": "108", "type": "number"},
                                                         {"name": "Agréabilité", "value": "2", "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "112", "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "3", "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "98", "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "2", "type": "number"}]},
                                                        "reports": {"items": [
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-fr-8bcbfdc2-a856-4e62-8422-be87ced05170",
                                                          "languageCode": "fr"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-de-DE-532e689a-5c9f-4b71-95ca-fc1b29e5d73a",
                                                          "languageCode": "de-DE"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-en-GB-d8618e65-1cec-4617-bd35-83b35e456426",
                                                          "languageCode": "en-GB"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-nl-9c32d551-e82e-445d-9e67-8f3b11486e94",
                                                          "languageCode": "nl"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-nl-BE-be2a6713-43bc-43e3-acc1-ff3489f05940",
                                                          "languageCode": "nl-BE"}]}}}]}]}}
